# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: videostreaming.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14videostreaming.proto\x12\x0evideostreaming\"\x1b\n\nVideoFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"\"\n\x0cVideoRequest\x12\x12\n\nvideo_name\x18\x01 \x01(\t2b\n\x15VideoStreamingService\x12I\n\x0bStreamVideo\x12\x1c.videostreaming.VideoRequest\x1a\x1a.videostreaming.VideoFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'videostreaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFRAME']._serialized_start=40
  _globals['_VIDEOFRAME']._serialized_end=67
  _globals['_VIDEOREQUEST']._serialized_start=69
  _globals['_VIDEOREQUEST']._serialized_end=103
  _globals['_VIDEOSTREAMINGSERVICE']._serialized_start=105
  _globals['_VIDEOSTREAMINGSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
