# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32}\n\x0b\x41uthService\x12\x36\n\rGenerateToken\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponse\x12\x36\n\x0bVerifyToken\x12\x12.auth.TokenRequest\x1a\x13.auth.TokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=20
  _globals['_AUTHREQUEST']._serialized_end=69
  _globals['_AUTHRESPONSE']._serialized_start=71
  _globals['_AUTHRESPONSE']._serialized_end=100
  _globals['_TOKENREQUEST']._serialized_start=102
  _globals['_TOKENREQUEST']._serialized_end=131
  _globals['_TOKENRESPONSE']._serialized_start=133
  _globals['_TOKENRESPONSE']._serialized_end=163
  _globals['_AUTHSERVICE']._serialized_start=165
  _globals['_AUTHSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
