# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\x10\x43onnectionStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"<\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\x9b\x01\n\x0b\x43hatService\x12\x31\n\x0b\x43onnectUser\x12\n.chat.User\x1a\x16.chat.ConnectionStatus\x12)\n\x0bSendMessage\x12\r.chat.Message\x1a\x0b.chat.Empty\x12.\n\x0fReceiveMessages\x12\n.chat.User\x1a\r.chat.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=40
  _globals['_CONNECTIONSTATUS']._serialized_start=42
  _globals['_CONNECTIONSTATUS']._serialized_end=94
  _globals['_MESSAGE']._serialized_start=96
  _globals['_MESSAGE']._serialized_end=156
  _globals['_EMPTY']._serialized_start=158
  _globals['_EMPTY']._serialized_end=165
  _globals['_CHATSERVICE']._serialized_start=168
  _globals['_CHATSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
